# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: macos-latest
    steps:
    - name: checkout
	    uses: actions/checkout@v3
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - uses: actions/setup-node@v2
        with:
          node-version: '12'
    - run: |
        npm install -g appium@v1.22.3
        appium -v
        appium &>/dev/null &
    - name: run tests
      uses: reactivecircus/android-emulator-runner@v2
      with:
        api-level: 30
		    target: [default]
        arch: x86_64
        profile: Pixel 2
        script: mvn clean test -Pandroid